### ISSUE TITLE
Актуализировать README.md

### ISSUE THREAD

**Issue by elenasheshukova** [ChervotkinaTeam/TodoList#26]
Добавить инструкцию для членов команды о настройке и разворачивании проекта.

**Comment by Koloma** [comment]
Предлагаю немного изменить форматирование инструкции:
1. Команду для установки линтера оформить блоком для кода (см. как сделан раздел Getting Started)
2. Также блоком для кода оформить скрипт для Build Phases
3. В некоторых словах пропущены буквы, при написании текстовой инструкции используй редактор с подсветкой ошибок (также можно и нужно в самом Xcode включить проверку орфографических ошибок, очень удобно)
